from pathlib import Path

#ROOT 
ROOT_DIR = Path(__file__).resolve().parent.parent

# DATA DIRECTORIES
DATA_DIR = ROOT_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
TRANSFORMED_DATA_DIR = DATA_DIR / "transformed"
CLEANED_DATA_DIR = DATA_DIR / "cleaned"

# VALIDATION DIRECTORIES
VALIDATION_DIR = ROOT_DIR / "validation"
VALIDATION_REPORT_DIR = VALIDATION_DIR / "reports"
PAPER_REPORT_DIR = VALIDATION_REPORT_DIR / "paper"
AUTHOR_REPORT_DIR = VALIDATION_REPORT_DIR / "author"
INSTITUTION_REPORT_DIR = VALIDATION_REPORT_DIR / "institution"

# CLEANING DIRECTORIES
CLEANING_DIR = ROOT_DIR / "cleaning"
CLEANING_CORRECTION_DIR = CLEANING_DIR / "corrections"
CLEANING_PAPER_DIR = CLEANING_CORRECTION_DIR / "paper"
CLEANING_INSTITUTION_DIR = CLEANING_CORRECTION_DIR / "institution"
CLEANING_TOPIC_DIR = CLEANING_CORRECTION_DIR / "topics"

# MODELS DIRECTORIES 
MODEL_DIR = ROOT_DIR / "saved_models"


# RESULTS DIRECTORIES
RESULT_DIR = ROOT_DIR / "results"
BERTOPIC_RESULT_DIR = RESULT_DIR / "bertopic"
NETWORKX_RESULT_DIR = RESULT_DIR / "networkx"   
KNOWLEDGE_GRAPH_RESULT_DIR = RESULT_DIR / "knowledge_graph"
